#!/usr/bin/env bash
# ============================================================
#  THE LAST LIGHTHOUSE — 9:16 vertical cut (Shorts / Reels)
#
#  Same pipeline as build_film.sh (Stage 6), reframed:
#   - Ken Burns becomes a slow HORIZONTAL PAN across each frame
#     (the 9:16 crop window travels left/right through the 16:9
#     composition — alternating direction per shot)
#   - 1080x1920 canvas, same crossfades, titles, VO + sound design
#
#  Re-run anytime:  ./build_vertical.sh   -> film-vertical.mp4
# ============================================================
set -euo pipefail
cd "$(dirname "$0")"

FF=""
if command -v ffmpeg >/dev/null 2>&1; then
  FF=$(command -v ffmpeg)
else
  FF=$(python3 - <<'EOF'
try:
    import imageio_ffmpeg
    print(imageio_ffmpeg.get_ffmpeg_exe())
except Exception:
    raise SystemExit(1)
EOF
)
fi
[ -n "$FF" ] || { echo "ERROR: ffmpeg not found. Try: pip install imageio-ffmpeg"; exit 1; }
echo "==> using ffmpeg: $FF"

FONT=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf
FILTER_LIST=$("$FF" -hide_banner -filters 2>/dev/null)
HAVE_DRAWTEXT=0; [[ " $FILTER_LIST " == *" drawtext "* ]] && HAVE_DRAWTEXT=1
HAVE_OVERLAY=0;  [[ " $FILTER_LIST " == *" overlay "* ]]  && HAVE_OVERLAY=1

FRAMES=(shot-01 shot-02 shot-03 shot-04 shot-05 shot-06 shot-07 shot-08)
WEIGHTS=(9 8 7 8 9 8 8 9)
XF=0.6
LEAD=2.5
TAIL=4.5
FPS=24
W=1080
H=1920
CW=608                 # 9:16 crop window taken from the 1920x1080 source
mkdir -p tmp

NDUR=$("$FF" -hide_banner -i audio/narration.mp3 -f null - 2>&1 \
        | grep -oE 'Duration: [0-9:.]+' | head -1 | awk '{print $2}')
N=$(echo "$NDUR" | awk -F: '{print $1*3600+$2*60+$3}')
TOTAL=$(awk -v l=$LEAD -v n=$N -v t=$TAIL 'BEGIN{printf "%.3f", l+n+t}')
echo "==> narration ${N}s -> vertical film target ${TOTAL}s"

awk -v total=$TOTAL -v xf=$XF -v w="${WEIGHTS[*]}" 'BEGIN{
  split(w,ws," "); s=0; for(i in ws) s+=ws[i];
  k=(total+7*xf)/s; for(i=1;i<=8;i++) printf "%.4f\n", ws[i]*k
}' > tmp/durs.txt
mapfile -t DURS < tmp/durs.txt

# ---- 1) vertical clips: crop a 9:16 window and PAN across the frame ----
for i in $(seq 0 7); do
  f=${FRAMES[$i]}; d=${DURS[$i]}
  F=$(awk -v d=$d -v fps=$FPS 'BEGIN{printf "%d", d*fps+0.5}')
  DURS[$i]=$(awk -v F=$F -v fps=$FPS 'BEGIN{printf "%.4f", F/fps}')
  if (( i % 2 == 0 )); then
    XP="min(max((in_w-out_w)*t/${DURS[$i]},0),in_w-out_w)"
  else
    XP="min(max((in_w-out_w)*(1-t/${DURS[$i]}),0),in_w-out_w)"
  fi
  VF="scale=1920:1080:force_original_aspect_ratio=increase,crop=1920:1080,scale=1920:1080:flags=lanczos,crop=${CW}:1080:x='${XP}':y=0,scale=${W}:${H}:flags=lanczos,setsar=1,format=yuv420p"
  echo "==> vclip $((i+1)) ${f}  (${DURS[$i]}s, ${F} frames)"
  "$FF" -y -hide_banner -loglevel error -framerate 24 -loop 1 -i "frames/${f}.png" \
        -vf "$VF" -frames:v "$F" -r $FPS \
        -c:v libx264 -preset medium -crf 18 "tmp/vclip-$i.mp4"
done
printf '%s\n' "${DURS[@]}" > tmp/durs.txt

OFFSETS=($(awk -v xf=$XF '{ d[NR]=$1 } END {
  o=0; for(i=1;i<NR;i++){ o+=d[i]-xf; printf "%.3f ", o }
}' tmp/durs.txt))

# ---- 2) title / credits on the vertical canvas ----
TITLE_MODE="none"
if [ "$HAVE_DRAWTEXT" = "1" ] && [ -f "$FONT" ]; then TITLE_MODE="drawtext"
elif [ "$HAVE_OVERLAY" = "1" ] && python3 -c "import PIL" 2>/dev/null; then TITLE_MODE="png"
fi
case "$TITLE_MODE" in
  png)
    python3 - "$FONT" "$W" "$H" <<'EOF'
import sys
from PIL import Image, ImageDraw, ImageFont
font_path, W, H = sys.argv[1], int(sys.argv[2]), int(sys.argv[3])

def draw_tracked(draw, xy, text, font, tracking):
    x, y = xy
    for ch in text:
        draw.text((x, y), ch, font=font, fill=(255, 255, 255, 255))
        x += font.getbbox(ch)[2] + tracking

def text_png(text, size, tracking, path, y):
    img = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    font = ImageFont.truetype(font_path, size)
    widths = [font.getbbox(ch)[2] + tracking for ch in text]
    total_w = sum(widths) - tracking
    draw_tracked(draw, ((W - total_w) // 2, y), text, font, tracking)
    img.save(path)

text_png("THE LAST LIGHTHOUSE", 74, 12, "tmp/title.png", H // 2 - 90)
text_png("WRITTEN, DIRECTED & GENERATED BY YOU", 30, 4, "tmp/credits.png", H // 2 - 15)
print("PIL vertical title PNGs rendered")
EOF
    "$FF" -y -hide_banner -loglevel error -f image2 -r 24 -loop 1 -i tmp/title.png \
      -vf "format=rgba,setsar=1,fade=t=in:st=0:d=0.8:alpha=1,fade=t=out:st=3.7:d=0.8:alpha=1" \
      -t 5.5 -r 24 -c:v qtrle tmp/title.mov
    "$FF" -y -hide_banner -loglevel error -f image2 -r 24 -loop 1 -i tmp/credits.png \
      -vf "format=rgba,setsar=1,fade=t=in:st=0:d=0.8:alpha=1,fade=t=out:st=2.0:d=0.8:alpha=1" \
      -t 3.6 -r 24 -c:v qtrle tmp/credits.mov
    ;;
esac

# ---- 3) STAGE A: crossfade chain (clips are already 9:16) ----
FADE_OUT=$(awk -v t=$TOTAL 'BEGIN{printf "%.3f", t-1.0}')
FILT=tmp/filterA.txt; : > "$FILT"
for i in $(seq 0 7); do
  O=0; [ "$i" -gt 0 ] && O=${OFFSETS[$((i-1))]}
  D=${DURS[$i]}
  S=$(awk -v t=$TOTAL -v o=$O -v d=$D 'BEGIN{printf "%.3f", t-o-d}')
  CHAIN="[$i:v]fps=24,format=yuva420p"
  if [ "$i" -gt 0 ]; then CHAIN="$CHAIN,fade=t=in:st=0:d=${XF}:alpha=1"; fi
  CHAIN="$CHAIN,tpad=start_duration=${O}:stop_duration=${S}:color=black@0[c$i];"
  echo "$CHAIN" >> "$FILT"
  if [ "$i" -gt 0 ]; then
    PREV="o$((i-1))"; [ "$i" -eq 1 ] && PREV="c0"
    echo "[$PREV][c$i]overlay=0:0:format=yuv420[o$i];" >> "$FILT"
  fi
done
echo "[o7]fade=t=in:st=0:d=0.8,fade=t=out:st=${FADE_OUT}:d=1.0[vout];" >> "$FILT"

echo "==> STAGE A: crossfade chain"
"$FF" -y -hide_banner -loglevel error \
  -reinit_filter 0 -i tmp/vclip-0.mp4 -reinit_filter 0 -i tmp/vclip-1.mp4 \
  -reinit_filter 0 -i tmp/vclip-2.mp4 -reinit_filter 0 -i tmp/vclip-3.mp4 \
  -reinit_filter 0 -i tmp/vclip-4.mp4 -reinit_filter 0 -i tmp/vclip-5.mp4 \
  -reinit_filter 0 -i tmp/vclip-6.mp4 -reinit_filter 0 -i tmp/vclip-7.mp4 \
  -filter_complex_script "$FILT" -map "[vout]" \
  -c:v libx264 -preset medium -crf 16 -pix_fmt yuv420p -r $FPS \
  -t "$TOTAL" \
  tmp/video-a.mp4

# ---- 4) STAGE B: overlays + narration + sound design ----
"$FF" -y -hide_banner -loglevel error -i audio/narration.mp3 -ar 48000 -c:a pcm_s16le tmp/narration.wav

CRED_IN=$(awk -v t=$TOTAL 'BEGIN{printf "%.3f", t-4.0}')
FILTB=tmp/filterB.txt; : > "$FILTB"
case "$TITLE_MODE" in
  png)
    echo "[0:v]format=yuv420p[vm];" >> "$FILTB"
    echo "[1:v]format=rgba,setpts=PTS-STARTPTS+1.0/TB[ti];" >> "$FILTB"
    echo "[vm][ti]overlay=0:0:format=yuv420[o1];" >> "$FILTB"
    echo "[o1]format=yuv420p[vm2];" >> "$FILTB"
    echo "[2:v]format=rgba,setpts=PTS-STARTPTS+${CRED_IN}/TB[cr];" >> "$FILTB"
    echo "[vm2][cr]overlay=0:0:format=yuv420[vout];" >> "$FILTB"
    ;;
  drawtext)
    echo "[0:v]drawtext=fontfile=${FONT}:text='THE LAST LIGHTHOUSE':fontsize=74:fontcolor=white:borderw=3:bordercolor=black@0.55:x=(w-text_w)/2:y=(h-text_h)/2-90:alpha='if(lt(t,1.0),0,if(lt(t,1.8),(t-1.0)/0.8,if(lt(t,4.7),1,if(lt(t,5.5),(5.5-t)/0.8,0))))'[t1];" >> "$FILTB"
    echo "[t1]drawtext=fontfile=${FONT}:text='WRITTEN, DIRECTED & GENERATED BY YOU':fontsize=30:fontcolor=white:borderw=2:bordercolor=black@0.55:x=(w-text_w)/2:y=(h-text_h)/2-15:alpha='if(lt(t,${CRED_IN}),0,if(lt(t,${CRED_IN}+0.8),(t-${CRED_IN})/0.8,if(lt(t,${CRED_IN}+2.0),1,if(lt(t,${CRED_IN}+2.8),(${CRED_IN}+2.8-t)/0.8,0))))'[t2];" >> "$FILTB"
    echo "[t2]format=yuv420p[vout];" >> "$FILTB"
    ;;
  *)
    echo "[0:v]format=yuv420p[vout];" >> "$FILTB"
    ;;
esac

AFOUT=$(awk -v l=$LEAD -v n=$N 'BEGIN{printf "%.3f", l+n-1.2}')
ADELAY=$(awk -v l=$LEAD 'BEGIN{printf "%.0f", l*1000}')
AIDX=1; [ "$TITLE_MODE" = "png" ] && AIDX=3
echo "[${AIDX}:a]adelay=delays=${ADELAY}:all=1,loudnorm=I=-14:TP=-1.5:LRA=11,afade=t=in:st=0:d=0.5,afade=t=out:st=${AFOUT}:d=1.2,aformat=channel_layouts=stereo[vo];" >> "$FILTB"

AMBFADE=$(awk -v t=$TOTAL 'BEGIN{printf "%.3f", t-3.0}')
BIDX=$((AIDX+1))
MIDX=$BIDX; [ -f audio/ambience.wav ] && MIDX=$((BIDX+1))
MIXPARTS="[vo]"; MIXIN=1
if [ -f audio/ambience.wav ]; then
  echo "[${BIDX}:a]afade=t=in:st=0:d=1.5,afade=t=out:st=${AMBFADE}:d=3.0,aformat=channel_layouts=stereo[bed];" >> "$FILTB"
  MIXPARTS="${MIXPARTS}[bed]"; MIXIN=$((MIXIN+1))
fi
if [ -f audio/music.wav ]; then
  echo "[${MIDX}:a]afade=t=in:st=0:d=2.0,afade=t=out:st=${AMBFADE}:d=3.0,aformat=channel_layouts=stereo[mus];" >> "$FILTB"
  MIXPARTS="${MIXPARTS}[mus]"; MIXIN=$((MIXIN+1))
fi
if [ "$MIXIN" -gt 1 ]; then
  echo "${MIXPARTS}amix=inputs=${MIXIN}:duration=longest:dropout_transition=0:normalize=0[aout];" >> "$FILTB"
else
  echo "[vo]anull[aout];" >> "$FILTB"
fi

echo "==> STAGE B: overlays + narration"
INPUTS=(-reinit_filter 0 -i tmp/video-a.mp4)
[ "$TITLE_MODE" = "png" ] && INPUTS+=(-reinit_filter 0 -i tmp/title.mov -reinit_filter 0 -i tmp/credits.mov)
INPUTS+=(-reinit_filter 0 -i tmp/narration.wav)
[ -f audio/ambience.wav ] && INPUTS+=(-reinit_filter 0 -i audio/ambience.wav)
[ -f audio/music.wav ] && INPUTS+=(-reinit_filter 0 -i audio/music.wav)

"$FF" -y -hide_banner -loglevel error \
  "${INPUTS[@]}" \
  -filter_complex_script "$FILTB" \
  -map "[vout]" -map "[aout]" \
  -c:v libx264 -preset medium -crf 19 -pix_fmt yuv420p -r $FPS \
  -c:a aac -b:a 192k -ar 48000 -movflags +faststart \
  -t "$TOTAL" \
  film-vertical.mp4

"$FF" -hide_banner -i film-vertical.mp4 2>&1 | grep -E 'Duration|Stream' | head -3
ls -lh film-vertical.mp4 | awk '{print "==> written:", $9, $5}'
echo "==> DONE. film-vertical.mp4 is the 9:16 Shorts cut."
